'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class GlobalResource
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MapWindow.GlobalResource", GetType(GlobalResource).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    Friend Shared ReadOnly Property _select() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("select", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property about() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("about", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property application_view_tile() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("application_view_tile", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property bookmark_manager() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("bookmark_manager", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property bookmarks_view() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("bookmarks_view", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Chart() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Chart", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property charts_properties() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("charts_properties", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Custom Projection.
    '''</summary>
    Friend Shared ReadOnly Property CustomProjection_Text() As String
        Get
            Return ResourceManager.GetString("CustomProjection.Text", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property deselect() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("deselect", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property deselect_all() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("deselect_all", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Dynamic visibility is enabled for this layer. Do you want to disable it and show this layer?.
    '''</summary>
    Friend Shared ReadOnly Property DisableDynamicVis_Text() As String
        Get
            Return ResourceManager.GetString("DisableDynamicVis.Text", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property documentation() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("documentation", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property export_georeferenced() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("export_georeferenced", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property export_map() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("export_map", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property filter() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("filter", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property group_collapse() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("group_collapse", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property group_expand() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("group_expand", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property group_open() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("group_open", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property icoFullExtent() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("icoFullExtent", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property icoLayerAdd() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("icoLayerAdd", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property icoLayerClear() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("icoLayerClear", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property icoLayerRemove() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("icoLayerRemove", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property icoNew() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("icoNew", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property icoSave() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("icoSave", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property icoZoom() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("icoZoom", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property icoZoomIn() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("icoZoomIn", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property icoZoomLayer() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("icoZoomLayer", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property icoZoomOut() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("icoZoomOut", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgAdd() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgAdd", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgBookmarkAdd() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgBookmarkAdd", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgBookmarkDelete() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgBookmarkDelete", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgBookmarkView() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgBookmarkView", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgClose() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgClose", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgCollapseAll() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgCollapseAll", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgCopy() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgCopy", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgCopyLegend() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgCopyLegend", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgDelete() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgDelete", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgDown() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgDown", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgExpandAll() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgExpandAll", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgExport() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgExport", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgFlash() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgFlash", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgFolder() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgFolder", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgGroupAdd() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgGroupAdd", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgGroupRemove() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgGroupRemove", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgHelp() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgHelp", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgHistory() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgHistory", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgInfo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgInfo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgKeyboard() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgKeyboard", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgLabel() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgLabel", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgLayerAdd() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgLayerAdd", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgLayerClear() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgLayerClear", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgLayerRemove() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgLayerRemove", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgMap() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgMap", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgMapExtents() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgMapExtents", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgMapPreview() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgMapPreview", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgMapScale() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgMapScale", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgMetadata() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgMetadata", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgNew() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgNew", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgOpenGroup() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgOpenGroup", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgPlugin() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgPlugin", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgPluginDisabled() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgPluginDisabled", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgPluginEdit() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgPluginEdit", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgPluginSub() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgPluginSub", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgPrinter() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgPrinter", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgProperties() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgProperties", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgRelabel() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgRelabel", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgSave() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgSave", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgSaveAs() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgSaveAs", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgScale() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgScale", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgScripts() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgScripts", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgSettings() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgSettings", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgTableEditor() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgTableEditor", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgUp() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgUp", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgUpdate() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgUpdate", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgWelcome() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgWelcome", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgZoomExtent() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgZoomExtent", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgZoomIn() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgZoomIn", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgZoomOut() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgZoomOut", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property imgZoomToLayer() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("imgZoomToLayer", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property label_edit() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("label_edit", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property label_properties() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("label_properties", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property label_reload() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("label_reload", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property layer_add() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("layer-add", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property layer_add_ecwp() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("layer_add_ecwp", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property layer_categories() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("layer_categories", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property layer_categories16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("layer-categories16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property layer_properties() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("layer-properties", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property layer_properties16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("layer-properties16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property layer_query() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("layer_query", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property layer_remove() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("layer-remove", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property layer_save() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("layer-save", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property layer_symbology() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("layer-symbology", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property layer_symbology16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("layer-symbology16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property legend() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("legend", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Legend.
    '''</summary>
    Friend Shared ReadOnly Property LegendName_Text() As String
        Get
            Return ResourceManager.GetString("LegendName.Text", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property length_measure() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("length-measure", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property mantis() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("mantis", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property map_export() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("map_export", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to About MapWindow.
    '''</summary>
    Friend Shared ReadOnly Property mnuAboutMapWindow_Text() As String
        Get
            Return ResourceManager.GetString("mnuAboutMapWindow.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Add ECWP Layer.
    '''</summary>
    Friend Shared ReadOnly Property mnuAddECWPLayer_Text() As String
        Get
            Return ResourceManager.GetString("mnuAddECWPLayer.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Add Layer.
    '''</summary>
    Friend Shared ReadOnly Property mnuAddLayer_Text() As String
        Get
            Return ResourceManager.GetString("mnuAddLayer.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delete Bookmarked View.
    '''</summary>
    Friend Shared ReadOnly Property mnuBookmarkDelete_Text() As String
        Get
            Return ResourceManager.GetString("mnuBookmarkDelete.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bookmarked Views.
    '''</summary>
    Friend Shared ReadOnly Property mnuBookmarkedViews_Text() As String
        Get
            Return ResourceManager.GetString("mnuBookmarkedViews.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bookmarks.
    '''</summary>
    Friend Shared ReadOnly Property mnuBookmarks_Text() As String
        Get
            Return ResourceManager.GetString("mnuBookmarks.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bookmarks Manager.
    '''</summary>
    Friend Shared ReadOnly Property mnuBookmarksManager_Text() As String
        Get
            Return ResourceManager.GetString("mnuBookmarksManager.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Add Bookmarked View.
    '''</summary>
    Friend Shared ReadOnly Property mnuBookmarkView_Text() As String
        Get
            Return ResourceManager.GetString("mnuBookmarkView.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Check for Updates.
    '''</summary>
    Friend Shared ReadOnly Property mnuCheckUpdates_Text() As String
        Get
            Return ResourceManager.GetString("mnuCheckUpdates.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Clear Selection of all layers.
    '''</summary>
    Friend Shared ReadOnly Property mnuClearAllSelection_Text() As String
        Get
            Return ResourceManager.GetString("mnuClearAllSelection.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Clear Layers.
    '''</summary>
    Friend Shared ReadOnly Property mnuClearLayer_Text() As String
        Get
            Return ResourceManager.GetString("mnuClearLayer.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Clear.
    '''</summary>
    Friend Shared ReadOnly Property mnuClearPreview_Text() As String
        Get
            Return ResourceManager.GetString("mnuClearPreview.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Clear Selected Shapes on current layer.
    '''</summary>
    Friend Shared ReadOnly Property mnuClearSelectedShapes_Text() As String
        Get
            Return ResourceManager.GetString("mnuClearSelectedShapes.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Close.
    '''</summary>
    Friend Shared ReadOnly Property mnuClose_Text() As String
        Get
            Return ResourceManager.GetString("mnuClose.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Contents.
    '''</summary>
    Friend Shared ReadOnly Property mnuContents_Text() As String
        Get
            Return ResourceManager.GetString("mnuContents.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Copy.
    '''</summary>
    Friend Shared ReadOnly Property mnuCopy_Text() As String
        Get
            Return ResourceManager.GetString("mnuCopy.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Legend.
    '''</summary>
    Friend Shared ReadOnly Property mnuCopyLegend_Text() As String
        Get
            Return ResourceManager.GetString("mnuCopyLegend.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Map.
    '''</summary>
    Friend Shared ReadOnly Property mnuCopyMap_Text() As String
        Get
            Return ResourceManager.GetString("mnuCopyMap.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to North Arrow.
    '''</summary>
    Friend Shared ReadOnly Property mnuCopyNorthArrow_Text() As String
        Get
            Return ResourceManager.GetString("mnuCopyNorthArrow.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Scale Bar.
    '''</summary>
    Friend Shared ReadOnly Property mnuCopyScaleBar_Text() As String
        Get
            Return ResourceManager.GetString("mnuCopyScaleBar.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to MapWindow Help.
    '''</summary>
    Friend Shared ReadOnly Property mnuDocs_Text() As String
        Get
            Return ResourceManager.GetString("mnuDocs.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Edit.
    '''</summary>
    Friend Shared ReadOnly Property mnuEdit_Text() As String
        Get
            Return ResourceManager.GetString("mnuEdit.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Edit Plug-ins.
    '''</summary>
    Friend Shared ReadOnly Property mnuEditPlugins_Text() As String
        Get
            Return ResourceManager.GetString("mnuEditPlugins.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exit.
    '''</summary>
    Friend Shared ReadOnly Property mnuExit_Text() As String
        Get
            Return ResourceManager.GetString("mnuExit.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Export.
    '''</summary>
    Friend Shared ReadOnly Property mnuExport_Text() As String
        Get
            Return ResourceManager.GetString("mnuExport.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to File.
    '''</summary>
    Friend Shared ReadOnly Property mnuFile_Text() As String
        Get
            Return ResourceManager.GetString("mnuFile.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Help.
    '''</summary>
    Friend Shared ReadOnly Property mnuHelp_Text() As String
        Get
            Return ResourceManager.GetString("mnuHelp.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Layer.
    '''</summary>
    Friend Shared ReadOnly Property mnuLayer_Text() As String
        Get
            Return ResourceManager.GetString("mnuLayer.Text", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property mnuLayerAdd() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("mnuLayerAdd", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Attribute Table.
    '''</summary>
    Friend Shared ReadOnly Property mnuLayerAttributeTable_Text() As String
        Get
            Return ResourceManager.GetString("mnuLayerAttributeTable.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Shapefile categories.
    '''</summary>
    Friend Shared ReadOnly Property mnuLayerCategories_Text() As String
        Get
            Return ResourceManager.GetString("mnuLayerCategories.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Charts properties.
    '''</summary>
    Friend Shared ReadOnly Property mnuLayerCharts_Text() As String
        Get
            Return ResourceManager.GetString("mnuLayerCharts.Text", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property mnuLayerClear() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("mnuLayerClear", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Labels properties.
    '''</summary>
    Friend Shared ReadOnly Property mnuLayerLabels_Text() As String
        Get
            Return ResourceManager.GetString("mnuLayerLabels.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Properties.
    '''</summary>
    Friend Shared ReadOnly Property mnuLayerProperties_Text() As String
        Get
            Return ResourceManager.GetString("mnuLayerProperties.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Relabel Shapefile.
    '''</summary>
    Friend Shared ReadOnly Property mnuLayerRelabel_Text() As String
        Get
            Return ResourceManager.GetString("mnuLayerRelabel.Text", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property mnuLayerRemove() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("mnuLayerRemove", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Legend Editor.
    '''</summary>
    Friend Shared ReadOnly Property mnuLegendEditor_Text() As String
        Get
            Return ResourceManager.GetString("mnuLegendEditor.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to New.
    '''</summary>
    Friend Shared ReadOnly Property mnuNew_Text() As String
        Get
            Return ResourceManager.GetString("mnuNew.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Next Zoom.
    '''</summary>
    Friend Shared ReadOnly Property mnuNextZoom_Text() As String
        Get
            Return ResourceManager.GetString("mnuNextZoom.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to MapWindow Documentation (Offline).
    '''</summary>
    Friend Shared ReadOnly Property mnuOfflineDocs_Text() As String
        Get
            Return ResourceManager.GetString("mnuOfflineDocs.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to MapWindow Documentation (Online).
    '''</summary>
    Friend Shared ReadOnly Property mnuOnlineDocs_Text() As String
        Get
            Return ResourceManager.GetString("mnuOnlineDocs.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Open Project.
    '''</summary>
    Friend Shared ReadOnly Property mnuOpen_Text() As String
        Get
            Return ResourceManager.GetString("mnuOpen.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Open Project Into New Group.
    '''</summary>
    Friend Shared ReadOnly Property mnuOpenProjectIntoGroup_Text() As String
        Get
            Return ResourceManager.GetString("mnuOpenProjectIntoGroup.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Symbology manager....
    '''</summary>
    Friend Shared ReadOnly Property mnuOptionsManager_Text() As String
        Get
            Return ResourceManager.GetString("mnuOptionsManager.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Panels.
    '''</summary>
    Friend Shared ReadOnly Property mnuPanels_Text() As String
        Get
            Return ResourceManager.GetString("mnuPanels.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Plug-ins.
    '''</summary>
    Friend Shared ReadOnly Property mnuPlugins_Text() As String
        Get
            Return ResourceManager.GetString("mnuPlugins.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Preview Map.
    '''</summary>
    Friend Shared ReadOnly Property mnuPreview_Text() As String
        Get
            Return ResourceManager.GetString("mnuPreview.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Previous Zoom.
    '''</summary>
    Friend Shared ReadOnly Property mnuPreviousZoom_Text() As String
        Get
            Return ResourceManager.GetString("mnuPreviousZoom.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Print.
    '''</summary>
    Friend Shared ReadOnly Property mnuPrint_Text() As String
        Get
            Return ResourceManager.GetString("mnuPrint.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Project.
    '''</summary>
    Friend Shared ReadOnly Property mnuProject_Text() As String
        Get
            Return ResourceManager.GetString("mnuProject.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Settings.
    '''</summary>
    Friend Shared ReadOnly Property mnuProjectSettings_Text() As String
        Get
            Return ResourceManager.GetString("mnuProjectSettings.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Build query.
    '''</summary>
    Friend Shared ReadOnly Property mnuQueryLayer_Text() As String
        Get
            Return ResourceManager.GetString("mnuQueryLayer.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Recent Projects.
    '''</summary>
    Friend Shared ReadOnly Property mnuRecentProjects_Text() As String
        Get
            Return ResourceManager.GetString("mnuRecentProjects.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Remove Group.
    '''</summary>
    Friend Shared ReadOnly Property mnuRemoveGroup_Text() As String
        Get
            Return ResourceManager.GetString("mnuRemoveGroup.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Remove Layer.
    '''</summary>
    Friend Shared ReadOnly Property mnuRemoveLayer_Text() As String
        Get
            Return ResourceManager.GetString("mnuRemoveLayer.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Panels.
    '''</summary>
    Friend Shared ReadOnly Property mnuRestoreMenu_Text() As String
        Get
            Return ResourceManager.GetString("mnuRestoreMenu.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Save.
    '''</summary>
    Friend Shared ReadOnly Property mnuSave_Text() As String
        Get
            Return ResourceManager.GetString("mnuSave.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Save As.
    '''</summary>
    Friend Shared ReadOnly Property mnuSaveAs_Text() As String
        Get
            Return ResourceManager.GetString("mnuSaveAs.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Georeferenced Map.
    '''</summary>
    Friend Shared ReadOnly Property mnuSaveGeorefMapImage_Text() As String
        Get
            Return ResourceManager.GetString("mnuSaveGeorefMapImage.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Legend.
    '''</summary>
    Friend Shared ReadOnly Property mnuSaveLegend_Text() As String
        Get
            Return ResourceManager.GetString("mnuSaveLegend.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Map.
    '''</summary>
    Friend Shared ReadOnly Property mnuSaveMapImage_Text() As String
        Get
            Return ResourceManager.GetString("mnuSaveMapImage.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to North Arrow.
    '''</summary>
    Friend Shared ReadOnly Property mnuSaveNorthArrow_Text() As String
        Get
            Return ResourceManager.GetString("mnuSaveNorthArrow.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Scale Bar.
    '''</summary>
    Friend Shared ReadOnly Property mnuSaveScaleBar_Text() As String
        Get
            Return ResourceManager.GetString("mnuSaveScaleBar.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Scripts.
    '''</summary>
    Friend Shared ReadOnly Property mnuScript_Text() As String
        Get
            Return ResourceManager.GetString("mnuScript.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Set Map Scale.
    '''</summary>
    Friend Shared ReadOnly Property mnuSetScale_Text() As String
        Get
            Return ResourceManager.GetString("mnuSetScale.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Keyboard Shortcuts.
    '''</summary>
    Friend Shared ReadOnly Property mnuShortcuts_Text() As String
        Get
            Return ResourceManager.GetString("mnuShortcuts.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Legend.
    '''</summary>
    Friend Shared ReadOnly Property mnuShowLegend_Text() As String
        Get
            Return ResourceManager.GetString("mnuShowLegend.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Preview Map.
    '''</summary>
    Friend Shared ReadOnly Property mnuShowPreviewMap_Text() As String
        Get
            Return ResourceManager.GetString("mnuShowPreviewMap.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Show Floating Scale Bar.
    '''</summary>
    Friend Shared ReadOnly Property mnuShowScaleBar_Text() As String
        Get
            Return ResourceManager.GetString("mnuShowScaleBar.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Update preview.
    '''</summary>
    Friend Shared ReadOnly Property mnuUpdatePreview_Text() As String
        Get
            Return ResourceManager.GetString("mnuUpdatePreview.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Update using Current View.
    '''</summary>
    Friend Shared ReadOnly Property mnuUpdatePreviewCurr_Text() As String
        Get
            Return ResourceManager.GetString("mnuUpdatePreviewCurr.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Update using Full Extents.
    '''</summary>
    Friend Shared ReadOnly Property mnuUpdatePreviewFull_Text() As String
        Get
            Return ResourceManager.GetString("mnuUpdatePreviewFull.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to View.
    '''</summary>
    Friend Shared ReadOnly Property mnuView_Text() As String
        Get
            Return ResourceManager.GetString("mnuView.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Welcome Screen.
    '''</summary>
    Friend Shared ReadOnly Property mnuWelcomeScreen_Text() As String
        Get
            Return ResourceManager.GetString("mnuWelcomeScreen.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Zoom In.
    '''</summary>
    Friend Shared ReadOnly Property mnuZoomIn_Text() As String
        Get
            Return ResourceManager.GetString("mnuZoomIn.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Zoom Out.
    '''</summary>
    Friend Shared ReadOnly Property mnuZoomOut_Text() As String
        Get
            Return ResourceManager.GetString("mnuZoomOut.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Zoom to Full Extents.
    '''</summary>
    Friend Shared ReadOnly Property mnuZoomToFullExtents_Text() As String
        Get
            Return ResourceManager.GetString("mnuZoomToFullExtents.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Zoom to group.
    '''</summary>
    Friend Shared ReadOnly Property mnuZoomToGroup_Text() As String
        Get
            Return ResourceManager.GetString("mnuZoomToGroup.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Zoom to Layer.
    '''</summary>
    Friend Shared ReadOnly Property mnuZoomToLayer_Text() As String
        Get
            Return ResourceManager.GetString("mnuZoomToLayer.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Zoom to Preview Map Extents.
    '''</summary>
    Friend Shared ReadOnly Property mnuZoomToPreviewExtents_Text() As String
        Get
            Return ResourceManager.GetString("mnuZoomToPreviewExtents.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Area of the drawn polygon: .
    '''</summary>
    Friend Shared ReadOnly Property msgAreaDrawnPolygon_Text() As String
        Get
            Return ResourceManager.GetString("msgAreaDrawnPolygon.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The submission failed.
    ''' The username or password is invalid. Please double-check it..
    '''</summary>
    Friend Shared ReadOnly Property msgBadUsernamePassword_Text() As String
        Get
            Return ResourceManager.GetString("msgBadUsernamePassword.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The change of language to {0} will take effect after restarting MapWindow.
    '''</summary>
    Friend Shared ReadOnly Property msgChangeLanguage_Text() As String
        Get
            Return ResourceManager.GetString("msgChangeLanguage.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Change Language.
    '''</summary>
    Friend Shared ReadOnly Property msgChangeLanguage_Title() As String
        Get
            Return ResourceManager.GetString("msgChangeLanguage.Title", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure you want to remove all layers?.
    '''</summary>
    Friend Shared ReadOnly Property msgClearLayers_Text() As String
        Get
            Return ResourceManager.GetString("msgClearLayers.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Click next point..
    '''</summary>
    Friend Shared ReadOnly Property msgClickNextPoint_Text() As String
        Get
            Return ResourceManager.GetString("msgClickNextPoint.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Custom.
    '''</summary>
    Friend Shared ReadOnly Property msgCustomProjection_Text() As String
        Get
            Return ResourceManager.GetString("msgCustomProjection.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thank you! The data has been submitted..
    '''</summary>
    Friend Shared ReadOnly Property msgDataSubmitted_Text() As String
        Get
            Return ResourceManager.GetString("msgDataSubmitted.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Click next point. Right-click to start over..
    '''</summary>
    Friend Shared ReadOnly Property msgDistanceStartOver_Text() As String
        Get
            Return ResourceManager.GetString("msgDistanceStartOver.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to One of the layers in the project was not found. The file that couldn&apos;t be located is: 
    '''{0} 
    '''Would you like to locate this file?
    '''
    '''No will simply drop the layer from the project, Cancel will drop all missing layers..
    '''</summary>
    Friend Shared ReadOnly Property msgDropMissingLayer_Text() As String
        Get
            Return ResourceManager.GetString("msgDropMissingLayer.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Missing Layer {0}.
    '''</summary>
    Friend Shared ReadOnly Property msgDropMissingLayer_Title() As String
        Get
            Return ResourceManager.GetString("msgDropMissingLayer.Title", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Error.
    '''</summary>
    Friend Shared ReadOnly Property msgError_Text() As String
        Get
            Return ResourceManager.GetString("msgError.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to There were errors saving the image.
    '''</summary>
    Friend Shared ReadOnly Property msgErrorSavingImage_Text() As String
        Get
            Return ResourceManager.GetString("msgErrorSavingImage.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to File Name: .
    '''</summary>
    Friend Shared ReadOnly Property msgFileName_Text() As String
        Get
            Return ResourceManager.GetString("msgFileName.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to File {0} not found.
    '''</summary>
    Friend Shared ReadOnly Property msgFileNotFound_Text() As String
        Get
            Return ResourceManager.GetString("msgFileNotFound.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You don&apos;t appear to have an active internet connection. Our documentation is available online at this URL:
    '''
    '''http://www.MapWindow.org/wiki/.
    '''</summary>
    Friend Shared ReadOnly Property msgFindDocumentation_Text() As String
        Get
            Return ResourceManager.GetString("msgFindDocumentation.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You don&apos;t appear to have an active internet connection. We have tutorials available at this URL:
    '''
    '''http://www.MapWindow.org/tutorials/.
    '''</summary>
    Friend Shared ReadOnly Property msgFindTutorials_Text() As String
        Get
            Return ResourceManager.GetString("msgFindTutorials.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The response from the server was not understood. Please try submitting again..
    '''</summary>
    Friend Shared ReadOnly Property msgGarbledServerResponse_Text() As String
        Get
            Return ResourceManager.GetString("msgGarbledServerResponse.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure you wish to remove the currently selected layer?.
    '''</summary>
    Friend Shared ReadOnly Property msgHandleShortcutKeys_Text() As String
        Get
            Return ResourceManager.GetString("msgHandleShortcutKeys.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Help file does not exist..
    '''</summary>
    Friend Shared ReadOnly Property msgHelpfileDoesNotExist_Text() As String
        Get
            Return ResourceManager.GetString("msgHelpfileDoesNotExist.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Content could not be read. Status Code={0}..
    '''</summary>
    Friend Shared ReadOnly Property msgHttpStatusCodeElse_Text() As String
        Get
            Return ResourceManager.GetString("msgHttpStatusCodeElse.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Content could not be read. URL not accessible. Status Code={0}..
    '''</summary>
    Friend Shared ReadOnly Property msgHttpStatusCodeNotFound_Text() As String
        Get
            Return ResourceManager.GetString("msgHttpStatusCodeNotFound.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Content could not be read. URL was changed. Status Code={0}..
    '''</summary>
    Friend Shared ReadOnly Property msgHttpStatusCodeRedirect_Text() As String
        Get
            Return ResourceManager.GetString("msgHttpStatusCodeRedirect.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Warning: Ignoring the script name provided on the command line because it doesn&apos;t exist..
    '''</summary>
    Friend Shared ReadOnly Property msgIgnoreScript_Text() As String
        Get
            Return ResourceManager.GetString("msgIgnoreScript.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to All fields are required; please make sure to enter something in every field..
    '''</summary>
    Friend Shared ReadOnly Property msgIncomplete_Text() As String
        Get
            Return ResourceManager.GetString("msgIncomplete.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Dynamic visibility is enabled for this layer. Do you want to disable it and show this layer?.
    '''</summary>
    Friend Shared ReadOnly Property msgLegend_LayerVisibleChanged_Text() As String
        Get
            Return ResourceManager.GetString("msgLegend_LayerVisibleChanged.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No properties available for this layer type..
    '''</summary>
    Friend Shared ReadOnly Property msgLegendLayerDoubleClick_Text() As String
        Get
            Return ResourceManager.GetString("msgLegendLayerDoubleClick.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to    Module Name:  .
    '''</summary>
    Friend Shared ReadOnly Property msgModuleName_Text() As String
        Get
            Return ResourceManager.GetString("msgModuleName.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Module Info:  .
    '''</summary>
    Friend Shared ReadOnly Property msgModulesInfo_Text() As String
        Get
            Return ResourceManager.GetString("msgModulesInfo.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to New Layer: .
    '''</summary>
    Friend Shared ReadOnly Property msgNewLayerProjection_Text() As String
        Get
            Return ResourceManager.GetString("msgNewLayerProjection.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You don&apos;t appear to have an active internet connection.
    '''
    '''Please check your internet connection and try again..
    '''</summary>
    Friend Shared ReadOnly Property msgNoConnection_Text() As String
        Get
            Return ResourceManager.GetString("msgNoConnection.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The currently loaded script will be overwritten. Do you want to continue?.
    '''</summary>
    Friend Shared ReadOnly Property msgOverwriteCurrentlyLoadedScript_Text() As String
        Get
            Return ResourceManager.GetString("msgOverwriteCurrentlyLoadedScript.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Area:.
    '''</summary>
    Friend Shared ReadOnly Property msgPanelArea_Text() As String
        Get
            Return ResourceManager.GetString("msgPanelArea.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Click on the vertices; right-click to finish.
    '''</summary>
    Friend Shared ReadOnly Property msgPanelAreaClick_Text() As String
        Get
            Return ResourceManager.GetString("msgPanelAreaClick.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Distance:.
    '''</summary>
    Friend Shared ReadOnly Property msgPanelDistance_Text() As String
        Get
            Return ResourceManager.GetString("msgPanelDistance.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to    Path:  .
    '''</summary>
    Friend Shared ReadOnly Property msgPath_Text() As String
        Get
            Return ResourceManager.GetString("msgPath.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Performance Info: (bytes).
    '''</summary>
    Friend Shared ReadOnly Property msgPerformanceInfo_Text() As String
        Get
            Return ResourceManager.GetString("msgPerformanceInfo.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to   Private Memory:  .
    '''</summary>
    Friend Shared ReadOnly Property msgPrivateMemory_Text() As String
        Get
            Return ResourceManager.GetString("msgPrivateMemory.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The project file could not be saved due to insufficient access
    '''
    '''Please have your system administrator grant access to the file:
    '''{0}.
    '''</summary>
    Friend Shared ReadOnly Property msgProjectInsufficientAccess_Text() As String
        Get
            Return ResourceManager.GetString("msgProjectInsufficientAccess.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Insufficient Access.
    '''</summary>
    Friend Shared ReadOnly Property msgProjectInsufficientAccess_Title() As String
        Get
            Return ResourceManager.GetString("msgProjectInsufficientAccess.Title", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Projection: .
    '''</summary>
    Friend Shared ReadOnly Property msgProjection_Text() As String
        Get
            Return ResourceManager.GetString("msgProjection.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Project Projection: .
    '''</summary>
    Friend Shared ReadOnly Property msgProjectProjection_Text() As String
        Get
            Return ResourceManager.GetString("msgProjectProjection.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The project file could not be saved because it is read-only
    '''
    '''Please have your system administrator grant write access to the file:
    '''{0}.
    '''</summary>
    Friend Shared ReadOnly Property msgProjectReadOnly_Text() As String
        Get
            Return ResourceManager.GetString("msgProjectReadOnly.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Read-Only Project File.
    '''</summary>
    Friend Shared ReadOnly Property msgProjectReadOnly_Title() As String
        Get
            Return ResourceManager.GetString("msgProjectReadOnly.Title", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure you want to remove the selected group and its layer(s)?.
    '''</summary>
    Friend Shared ReadOnly Property msgRemoveGroup_Text() As String
        Get
            Return ResourceManager.GetString("msgRemoveGroup.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Error: The reprojected grid file doesn&apos;t exist! Check for an errorlog.txt. Aborting layer add..
    '''</summary>
    Friend Shared ReadOnly Property msgReprojectedGridDoesNotExists_Text() As String
        Get
            Return ResourceManager.GetString("msgReprojectedGridDoesNotExists.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Do you wish to save your current script first?.
    '''</summary>
    Friend Shared ReadOnly Property msgSaveCurrentScript_Text() As String
        Get
            Return ResourceManager.GetString("msgSaveCurrentScript.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Layer {0} is in memory. Do you want to save it?.
    '''</summary>
    Friend Shared ReadOnly Property msgSaveInMemoryLayer_Text() As String
        Get
            Return ResourceManager.GetString("msgSaveInMemoryLayer.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Save Layer.
    '''</summary>
    Friend Shared ReadOnly Property msgSaveInMemoryLayer_Title() As String
        Get
            Return ResourceManager.GetString("msgSaveInMemoryLayer.Title", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Do you want to save the changes to .
    '''</summary>
    Friend Shared ReadOnly Property msgSaveProject1_Text() As String
        Get
            Return ResourceManager.GetString("msgSaveProject1.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to this project?.
    '''</summary>
    Friend Shared ReadOnly Property msgSaveProject2_Text() As String
        Get
            Return ResourceManager.GetString("msgSaveProject2.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Script Error.
    '''</summary>
    Friend Shared ReadOnly Property msgScriptError_Text() As String
        Get
            Return ResourceManager.GetString("msgScriptError.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nonexistant Script Passed.
    '''</summary>
    Friend Shared ReadOnly Property msgScriptNotExists_Text() As String
        Get
            Return ResourceManager.GetString("msgScriptNotExists.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Down Arrow - Pan Down (25% of View).
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsArrowDown_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsArrowDown.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Left Arrow - Pan Left (25% of View).
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsArrowLeft_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsArrowLeft.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Right Arrow - Pan Right (25% of View).
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsArrowRight_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsArrowRight.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Up Arrow - Pan Up (25% of View).
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsArrowUp_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsArrowUp.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ctrl-Up, Ctrl-Down: Switch selected layer in legend.
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsCtrlArrows_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsCtrlArrows.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ctrl-C - Copy a map snapshot to the clipboard..
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsCtrlC_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsCtrlC.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ctrl-Enter - Layer Properties.
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsCtrlEnter_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsCtrlEnter.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ctrl-F4 - Close the current project..
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsCtrlF4_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsCtrlF4.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ctrl-H - Shape Selection/Highlight Mode.
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsCtrlH_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsCtrlH.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ctrl-Home - Zoom to Selected Layer.
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsCtrlHome_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsCtrlHome.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ctrl-I - Feature Identifier Mode.
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsCtrlI_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsCtrlI.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ctrl-O - Open a project..
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsCtrlO_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsCtrlO.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ctrl-P - Open the Print Preview window.
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsCtrlP_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsCtrlP.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ctrl-S - Save the project..
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsCtrlS_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsCtrlS.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ctrl-Shift-I - Enter Zoom In mode..
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsCtrlShiftI_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsCtrlShiftI.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ctrl-Shift-O - Enter Zoom Out mode..
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsCtrlShiftO_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsCtrlShiftO.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ctrl-Shift-P - Enter Pan mode..
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsCtrlShiftP_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsCtrlShiftP.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ctrl-Spacebar: Toggle visibility on layer.
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsCtrlSpace_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsCtrlSpace.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Del - Remove the currently selected layer..
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsDel_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsDel.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Home - Zoom to Full Extents.
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsHome_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsHome.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ins - Add a layer..
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsIns_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsIns.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Minus - Zoom out on center of map (25% of View).
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsMinus_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsMinus.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Page-Down - Pan Down (50% of View).
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsPageDown_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsPageDown.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Page-Up - Pan Up (50% of View).
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsPageUp_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsPageUp.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Plus - Zoom in on center of map (25% of View).
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsPlus_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsPlus.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The following keyboard shortcuts are available:.
    '''</summary>
    Friend Shared ReadOnly Property msgShortcutsTitle_Text() As String
        Get
            Return ResourceManager.GetString("msgShortcutsTitle.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The submission succeeded. Thank you!.
    '''</summary>
    Friend Shared ReadOnly Property msgSubmittedSuccessfully_Text() As String
        Get
            Return ResourceManager.GetString("msgSubmittedSuccessfully.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to    CPU-Time: .
    '''</summary>
    Friend Shared ReadOnly Property msgTotalCpuTime_Text() As String
        Get
            Return ResourceManager.GetString("msgTotalCpuTime.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to    CPU-Time by user: .
    '''</summary>
    Friend Shared ReadOnly Property msgTotalUserModeCpuTime_Text() As String
        Get
            Return ResourceManager.GetString("msgTotalUserModeCpuTime.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The Update Check tool could not be located; all updates will need to be manually downloaded. {0} Open the Downloads page now?.
    '''</summary>
    Friend Shared ReadOnly Property msgUpdateToolNotFound_Text() As String
        Get
            Return ResourceManager.GetString("msgUpdateToolNotFound.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to    Version:  .
    '''</summary>
    Friend Shared ReadOnly Property msgVersion_Text() As String
        Get
            Return ResourceManager.GetString("msgVersion.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to    Virtual Memory:  .
    '''</summary>
    Friend Shared ReadOnly Property msgVirtualMemory_Text() As String
        Get
            Return ResourceManager.GetString("msgVirtualMemory.Text", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property northArrow() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("northArrow", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property open() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("open", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property pan() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("pan", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property panels() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("panels", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property paypal() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("paypal", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Author:  .
    '''</summary>
    Friend Shared ReadOnly Property PluginPropertyAuthor_Text() As String
        Get
            Return ResourceManager.GetString("PluginPropertyAuthor.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Build Date: .
    '''</summary>
    Friend Shared ReadOnly Property PluginPropertyBuildDate_Text() As String
        Get
            Return ResourceManager.GetString("PluginPropertyBuildDate.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Description:  .
    '''</summary>
    Friend Shared ReadOnly Property PluginPropertyDescription_Text() As String
        Get
            Return ResourceManager.GetString("PluginPropertyDescription.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Name:  .
    '''</summary>
    Friend Shared ReadOnly Property PluginPropertyName_Text() As String
        Get
            Return ResourceManager.GetString("PluginPropertyName.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Version:  .
    '''</summary>
    Friend Shared ReadOnly Property PluginPropertyVersion_Text() As String
        Get
            Return ResourceManager.GetString("PluginPropertyVersion.Text", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property print() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("print", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property project() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("project", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property project_settings() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("project-settings", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property projections_edit() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("projections_edit", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property quit() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("quit", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property recent_maps() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("recent_maps", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property remove_all_layers() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("remove-all-layers", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property save_as() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("save_as", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property saveNew() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("saveNew", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Change Display Units.
    '''</summary>
    Friend Shared ReadOnly Property sbContextMenu_ChangeUnits_Text() As String
        Get
            Return ResourceManager.GetString("sbContextMenu_ChangeUnits.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Choose Background Color.
    '''</summary>
    Friend Shared ReadOnly Property sbContextMenu_ChooseBackcolor_Text() As String
        Get
            Return ResourceManager.GetString("sbContextMenu_ChooseBackcolor.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Choose Text Color.
    '''</summary>
    Friend Shared ReadOnly Property sbContextMenu_ChooseForecolor_Text() As String
        Get
            Return ResourceManager.GetString("sbContextMenu_ChooseForecolor.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Place in Lower Left.
    '''</summary>
    Friend Shared ReadOnly Property sbContextMenu_LowerLeft_Text() As String
        Get
            Return ResourceManager.GetString("sbContextMenu_LowerLeft.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Place in Lower Right.
    '''</summary>
    Friend Shared ReadOnly Property sbContextMenu_LowerRight_Text() As String
        Get
            Return ResourceManager.GetString("sbContextMenu_LowerRight.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Place in Upper Left.
    '''</summary>
    Friend Shared ReadOnly Property sbContextMenu_UpperLeft_Text() As String
        Get
            Return ResourceManager.GetString("sbContextMenu_UpperLeft.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Place in Upper Right.
    '''</summary>
    Friend Shared ReadOnly Property sbContextMenu_UpperRight_Text() As String
        Get
            Return ResourceManager.GetString("sbContextMenu_UpperRight.Text", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property scale_bar() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("scale-bar", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property scale_bar_add() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("scale-bar-add", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property script_code() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("script_code", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property selectNew() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("selectNew", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property set_map_scale() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("set_map_scale", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property SymbologyManager() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("SymbologyManager", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property table_edit() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("table_edit", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property table_editor() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("table_editor", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property table_editor16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("table-editor16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property tableNew() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("tableNew", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Confirm remove all layers.
    '''</summary>
    Friend Shared ReadOnly Property titleClearLayers_Text() As String
        Get
            Return ResourceManager.GetString("titleClearLayers.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Error Saving image.
    '''</summary>
    Friend Shared ReadOnly Property titleErrorSavingImage_Text() As String
        Get
            Return ResourceManager.GetString("titleErrorSavingImage.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Helpfile is missing.
    '''</summary>
    Friend Shared ReadOnly Property titleHelpfileDoesNotExist_Text() As String
        Get
            Return ResourceManager.GetString("titleHelpfileDoesNotExist.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No Internet Connection.
    '''</summary>
    Friend Shared ReadOnly Property titleNoConnection_Text() As String
        Get
            Return ResourceManager.GetString("titleNoConnection.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Remove Group?.
    '''</summary>
    Friend Shared ReadOnly Property titleRemoveGroup_Text() As String
        Get
            Return ResourceManager.GetString("titleRemoveGroup.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Zoom to Layer.
    '''</summary>
    Friend Shared ReadOnly Property ToolStripMenuItem6_Text() As String
        Get
            Return ResourceManager.GetString("ToolStripMenuItem6.Text", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property tutorials() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("tutorials", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to User Defined.
    '''</summary>
    Friend Shared ReadOnly Property UserDefined_Text() As String
        Get
            Return ResourceManager.GetString("UserDefined.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Warning: No Projection on Layer.
    '''</summary>
    Friend Shared ReadOnly Property WarningNoProjectionOnLayer_Text() As String
        Get
            Return ResourceManager.GetString("WarningNoProjectionOnLayer.Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Warning: Projection Mismatch.
    '''</summary>
    Friend Shared ReadOnly Property WarningProjectionMismatch_Text() As String
        Get
            Return ResourceManager.GetString("WarningProjectionMismatch.Text", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property welcome() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("welcome", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property zoom_extentNew() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("zoom-extentNew", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property zoom_inNew() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("zoom-inNew", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property zoom_lastNew() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("zoom-lastNew", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property zoom_layerNew() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("zoom-layerNew", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property zoom_nextNew() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("zoom-nextNew", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property zoom_outNew() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("zoom-outNew", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property zoom_selectionNew() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("zoom-selectionNew", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
